/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface GcAlert {
        /**
          * The content of alert
         */
        "content"?: string;
        /**
          * The type of alert: info | success | error
         */
        "type"?: string;
    }
    interface GcButton {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * Is disabled
         */
        "disabled"?: boolean;
        /**
          * The id
         */
        "gcId": string;
        /**
          * height
         */
        "height"?: string;
        /**
          * href
         */
        "href"?: string;
        /**
          * Icon name
         */
        "icon"?: string;
        /**
          * padding text
         */
        "paddingText"?: string;
        /**
          * target
         */
        "target"?: string;
        /**
          * The type name
         */
        "type": string;
    }
    interface GcCellExpandable {
        /**
          * close the step item
         */
        "closeItem": () => Promise<void>;
        /**
          * Disabled in step
         */
        "disabled": boolean;
        "fieldName": string;
        /**
          * index of step item from top to bottom
         */
        "index": string;
        "maxHeight": string;
        "maxWidth": string;
        /**
          * The mutation observer config to listen for content changes in the step item
         */
        "mutationObserverConfig": { childList: boolean; subtree: boolean; };
        "numberOfEntryPerPage": number;
        /**
          * step item is open or opening (css transition)
         */
        "open": boolean;
        /**
          * open the step item
         */
        "openItem": () => Promise<void>;
        /**
          * Should open in step
         */
        "shouldOpen": boolean;
        /**
          * The status in step
         */
        "status": string;
        /**
          * The tooltip message
         */
        "tooltipMessage": string;
        "total": number;
        /**
          * The total text
         */
        "totalText": string;
        "value": string;
    }
    interface GcCellInvalid {
        /**
          * The error message
         */
        "message"?: string;
        /**
          * The tooltip position
         */
        "tooltipPosition": string;
    }
    interface GcCheckbox {
        /**
          * Is checked ?
         */
        "checked": boolean;
        /**
          * The class name
         */
        "class"?: string;
        /**
          * Is disabled ?
         */
        "disabled": boolean;
        /**
          * The id
         */
        "gcId": string;
        /**
          * The name of checkbox
         */
        "gcName": string;
        /**
          * The label of checkbox
         */
        "label"?: string;
    }
    interface GcDragContainer {
        "classContainer": string;
        "classDaggable": string;
        "group": string;
    }
    interface GcDraggableItem {
    }
    interface GcDropdown {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        "isOpen": boolean;
        "items": any[];
        /**
          * Positions    | 'auto'    | 'auto-left'    | 'auto-right'    | 'top'    | 'top-left'    | 'top-right'    | 'bottom'    | 'bottom-left'    | 'bottom-right'    | 'right'    | 'right-start'    | 'right-end'    | 'left'    | 'left-start'    | 'left-end'
         */
        "positions": string;
        /**
          * The button size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg';
        "trigger": 'click' | 'hover';
    }
    interface GcFormField {
        /**
          * Specifies the visible width of a text area
         */
        "cols"?: number;
        /**
          * Default value
         */
        "defaultValue"?: string;
        /**
          * Is disabled ?
         */
        "disabled"?: boolean;
        /**
          * Error text
         */
        "errorText": string;
        /**
          * The field id
         */
        "gcId"?: string;
        /**
          * The field name
         */
        "gcName"?: string;
        /**
          * Height of textarea
         */
        "height"?: string;
        /**
          * Info text
         */
        "infoText": string;
        /**
          * Is error
         */
        "isError": boolean;
        /**
          * [{   label: 'Shivaji Varma',   value: 'shivaji-varma' }]
         */
        "items": string | [];
        /**
          * The label name
         */
        "label"?: string;
        /**
          * Specifies the maximum number of characters allowed in the text area
         */
        "maxlength"?: number;
        /**
          * The placeholder
         */
        "placeholder"?: string;
        /**
          * Prefix icon
         */
        "prefixIcon": string;
        /**
          * Resize in textarea
         */
        "resize"?: string;
        /**
          * Specifies the visible number of lines in a text area
         */
        "rows"?: number;
        /**
          * Search type Possible values are `"none"`, `"initial"`, `"contains"`, `"managed"`. Defaults to `"none"`.
         */
        "search": 'none' | 'initial' | 'contains' | 'managed';
        /**
          * The input type
         */
        "type": string;
        /**
          * The input value
         */
        "value"?: string;
    }
    interface GcH1 {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The id
         */
        "gcId": string;
    }
    interface GcH2 {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The id
         */
        "gcId": string;
    }
    interface GcH3 {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The id
         */
        "gcId": string;
    }
    interface GcIcon {
        "color": string;
        "fontWeight": string;
        "name": string;
        /**
          * The Icon size. Possible values are: `"sm"`, `"md"`, `"lg"`, `"xl"` and size in pixel. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg' | 'xl' | string;
    }
    interface GcInput {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * Is disabled ?
         */
        "disabled"?: boolean;
        /**
          * The id
         */
        "gcId"?: string;
        /**
          * The name of input
         */
        "gcName"?: string;
        /**
          * Is error
         */
        "isError"?: boolean;
        /**
          * The placeholder
         */
        "placeholder"?: string;
        /**
          * The name of input
         */
        "prefixIcon"?: string;
        /**
          * The input type
         */
        "type": string;
        /**
          * The input value
         */
        "value"?: string;
    }
    interface GcLabel {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * Label for what component
         */
        "gcFor": string;
        /**
          * The id
         */
        "gcId": string;
    }
    interface GcLink {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The color of link
         */
        "color": string;
        /**
          * The id
         */
        "gcId"?: string;
        /**
          * Go to link
         */
        "gcTo"?: string;
        /**
          * Icon name
         */
        "icon"?: string;
        /**
          * Size of link
         */
        "size"?: string;
        /**
          * target link
         */
        "target"?: string;
    }
    interface GcMenu {
        "empty": boolean;
        "emptyState": any;
        /**
          * Sets focus on first menu item. Use this method instead of the global `element.focus()`.
         */
        "setFocus": () => Promise<void>;
        "showLoader": boolean;
        "value"?: string | number;
    }
    interface GcMenuItem {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The color of text
         */
        "color"?: string;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        /**
          * The color of dot
         */
        "dot"?: string;
        /**
          * The id
         */
        "gcId": string;
        /**
          * The label
         */
        "label"?: string;
        /**
          * Menu item selection state.
         */
        "selected": boolean;
        /**
          * Sets blur on the native `input` in `goat-input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input` in `goat-input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * The menu item value.
         */
        "value"?: string | number | null;
    }
    interface GcModal {
        /**
          * Header Icon
         */
        "headerIcon"?: string;
        /**
          * Is custom content?
         */
        "isCustomContent": boolean;
        /**
          * Is open?
         */
        "open": boolean;
        /**
          * Is transparent?
         */
        "transparent": boolean;
        /**
          * Width of modal
         */
        "width": string;
    }
    interface GcOl {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The id
         */
        "gcId": string;
    }
    interface GcPagination {
        /**
          * The page size
         */
        "activePage": number;
        /**
          * The page size
         */
        "pageSize": number;
        /**
          * The total
         */
        "total": number;
    }
    interface GcProgress {
        /**
          * The percent of progress
         */
        "percent"?: number;
        /**
          * The width of progress
         */
        "width"?: string;
    }
    interface GcSelect {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * If `true`, a clear icon will appear in the input when there is a value. Clicking it clears the input.
         */
        "clearable": boolean;
        "configAria": any;
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `goatChange` event after each keystroke.
         */
        "debounce": number;
        /**
          * Default value
         */
        "defaultValue"?: string;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        /**
          * The id
         */
        "gcId": string;
        /**
          * Is error
         */
        "isError"?: boolean;
        "isOpen": boolean;
        /**
          * [{   label: 'Shivaji Varma',   value: 'shivaji-varma' }]
         */
        "items": string | [];
        "multiple": boolean;
        /**
          * The input field placeholder.
         */
        "placeholder": string;
        "positions": string;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "readonly": boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
         */
        "required": boolean;
        /**
          * Search type Possible values are `"none"`, `"initial"`, `"contains"`, `"managed"`. Defaults to `"none"`.
         */
        "search": 'none' | 'initial' | 'contains' | 'managed';
        /**
          * Sets blur on the native `input` in `goat-input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input` in `ion-input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        "showLoader": boolean;
        /**
          * The select input size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * The input state. Possible values are: `"success"`, `"error"`, `"warning"`, 'default'. Defaults to `"default"`.
         */
        "state": 'success' | 'error' | 'warning' | 'default';
        /**
          * The input field value.
         */
        "value"?: string | number;
    }
    interface GcSpinner {
        /**
          * Is float above background
         */
        "isFloat": boolean;
    }
    interface GcStep {
        /**
          * before open the step item
         */
        "beforeOpenItem": () => Promise<void>;
        /**
          * close the step item
         */
        "closeItem": () => Promise<void>;
        /**
          * Customize in step opening
         */
        "customOpen": boolean;
        /**
          * Disabled in step
         */
        "disabled": boolean;
        /**
          * The icon in step
         */
        "icon": string;
        /**
          * index of step item from top to bottom
         */
        "index": string;
        "maxHeight": string;
        /**
          * The mutation observer config to listen for content changes in the step item
         */
        "mutationObserverConfig": { childList: boolean; subtree: boolean; };
        /**
          * step item is open or opening (css transition)
         */
        "open": boolean;
        /**
          * open the step item
         */
        "openItem": () => Promise<void>;
        /**
          * Should open in step
         */
        "shouldOpen": boolean;
        /**
          * The status in step
         */
        "status": string;
    }
    interface GcSteps {
        /**
          * close an step item
          * @param index
         */
        "close": (index: number) => Promise<void>;
        "customOpen": boolean;
        /**
          * Open an step item
          * @param index
         */
        "open": (index: number) => Promise<void>;
    }
    interface GcTab {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled": boolean;
        /**
          * The icon of tab.
         */
        "icon"?: string;
        /**
          * Button selection state.
         */
        "selected": boolean;
        "setFocus": () => Promise<void>;
        /**
          * Show loader.
         */
        "showLoader": boolean;
        "target": string;
        "triggerClick": () => Promise<void>;
        "value": string;
    }
    interface GcTabPanel {
        "active": boolean;
        "value": string;
    }
    interface GcTable {
        "background"?: string;
        /**
          * Grid columns configuration. [ {   "name":"name",   "label":"Name",   "width":300,   "fixed":true  }, {   "name":"age",   "label":"Age" } ]
         */
        "columns": string | any[];
        "customEmptyState"?: string;
        "customRows"?: string[];
        "customRowsBackground"?: string;
        "customRowsBorder"?: string;
        /**
          * Grid data to display on table [{  'id': '5e7118ddce4b3d577956457f',  'age': 21,  'name': 'John',  'company': 'India',  'email': 'john@example.com',  'phone': '+1 (839) 560-3581',  'address': '326 Irving Street, Grimsley, Texas, 4048'  }]
         */
        "data": string | any[];
        "emptyState": any;
        "gcId": string;
        "isBordered"?: boolean;
        "isCustomHeader": boolean;
        "isExpandable": boolean;
        "isLoading"?: false;
        "isNoBorderedAll"?: boolean;
        "isNoBorderedEmptyState": boolean;
        "isStripe"?: boolean;
        "keyField": string;
        "loadingGroupIndex": any[];
        "maxHeight": string;
        "maxWidthInExpandRow": string;
        "page": number;
        "pageSize": number;
        "paginate": boolean;
        "selectedRowKeys": string[];
        "selectionType": 'checkbox' | undefined;
        "serverSide": boolean;
        "settingColumns"?: boolean;
        "settingTable"?: any;
        "sortBy": string;
        "sortOrder": 'asc' | 'desc' | '';
        "sortable": boolean;
        "totalItems": number;
        "treeData": string | any[];
    }
    interface GcTabs {
    }
    interface GcTabsList {
        "managed": boolean;
        "variant": 'line' | 'contained';
    }
    interface GcTag {
        /**
          * The background of badge
         */
        "background": string;
        /**
          * The border color of badge
         */
        "borderColor": string;
        /**
          * The border width of badge
         */
        "borderWidth": string;
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The color of badge
         */
        "color": string;
        /**
          * The id
         */
        "gcId": string;
        /**
          * The width of badge
         */
        "height": string;
        /**
          * The type name
         */
        "type": string;
        /**
          * The width of badge
         */
        "width": string;
    }
    interface GcTextarea {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * Specifies the visible width of a text area
         */
        "cols"?: number;
        /**
          * Is disabled ?
         */
        "disabled"?: boolean;
        /**
          * The id
         */
        "gcId"?: string;
        /**
          * The name of input
         */
        "gcName"?: string;
        /**
          * Height of textarea
         */
        "height"?: string;
        /**
          * Is error
         */
        "isError"?: boolean;
        /**
          * Specifies the maximum number of characters allowed in the text area
         */
        "maxlength"?: number;
        /**
          * The placeholder
         */
        "placeholder"?: string;
        /**
          * Resize in textarea
         */
        "resize"?: string;
        /**
          * Specifies the visible number of lines in a text area
         */
        "rows"?: number;
        /**
          * The input value
         */
        "value"?: string;
    }
    interface GcTooltip {
        /**
          * The content
         */
        "content"?: any;
        /**
          * Is Copy Text?
         */
        "isCopyText"?: any;
        /**
          * Is Long Text?
         */
        "isLongText": boolean;
        /**
          * Is Popover?
         */
        "isPopover": boolean;
        /**
          * Is Toggle?
         */
        "isToggle": boolean;
        /**
          * Right position
         */
        "rightPos": string;
        /**
          * Top position
         */
        "topPos": string;
    }
    interface GcUl {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The id
         */
        "gcId": string;
    }
    interface GcUpload {
        /**
          * Accept type
         */
        "acceptType"?: string;
        /**
          * Disabled
         */
        "disabled"?: boolean;
        /**
          * Custom how to display
         */
        "isCustom"?: boolean;
        /**
          * Option
         */
        "option"?: {};
        /**
          * Width of upload
         */
        "width"?: string;
    }
}
export interface GcButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcButtonElement;
}
export interface GcCellExpandableCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcCellExpandableElement;
}
export interface GcCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcCheckboxElement;
}
export interface GcDragContainerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcDragContainerElement;
}
export interface GcFormFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcFormFieldElement;
}
export interface GcInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcInputElement;
}
export interface GcMenuItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcMenuItemElement;
}
export interface GcModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcModalElement;
}
export interface GcPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcPaginationElement;
}
export interface GcSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcSelectElement;
}
export interface GcStepCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcStepElement;
}
export interface GcStepsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcStepsElement;
}
export interface GcTabCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcTabElement;
}
export interface GcTableCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcTableElement;
}
export interface GcTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcTabsElement;
}
export interface GcTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcTextareaElement;
}
export interface GcTooltipCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcTooltipElement;
}
export interface GcUploadCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcUploadElement;
}
declare global {
    interface HTMLGcAlertElement extends Components.GcAlert, HTMLStencilElement {
    }
    var HTMLGcAlertElement: {
        prototype: HTMLGcAlertElement;
        new (): HTMLGcAlertElement;
    };
    interface HTMLGcButtonElement extends Components.GcButton, HTMLStencilElement {
    }
    var HTMLGcButtonElement: {
        prototype: HTMLGcButtonElement;
        new (): HTMLGcButtonElement;
    };
    interface HTMLGcCellExpandableElement extends Components.GcCellExpandable, HTMLStencilElement {
    }
    var HTMLGcCellExpandableElement: {
        prototype: HTMLGcCellExpandableElement;
        new (): HTMLGcCellExpandableElement;
    };
    interface HTMLGcCellInvalidElement extends Components.GcCellInvalid, HTMLStencilElement {
    }
    var HTMLGcCellInvalidElement: {
        prototype: HTMLGcCellInvalidElement;
        new (): HTMLGcCellInvalidElement;
    };
    interface HTMLGcCheckboxElement extends Components.GcCheckbox, HTMLStencilElement {
    }
    var HTMLGcCheckboxElement: {
        prototype: HTMLGcCheckboxElement;
        new (): HTMLGcCheckboxElement;
    };
    interface HTMLGcDragContainerElement extends Components.GcDragContainer, HTMLStencilElement {
    }
    var HTMLGcDragContainerElement: {
        prototype: HTMLGcDragContainerElement;
        new (): HTMLGcDragContainerElement;
    };
    interface HTMLGcDraggableItemElement extends Components.GcDraggableItem, HTMLStencilElement {
    }
    var HTMLGcDraggableItemElement: {
        prototype: HTMLGcDraggableItemElement;
        new (): HTMLGcDraggableItemElement;
    };
    interface HTMLGcDropdownElement extends Components.GcDropdown, HTMLStencilElement {
    }
    var HTMLGcDropdownElement: {
        prototype: HTMLGcDropdownElement;
        new (): HTMLGcDropdownElement;
    };
    interface HTMLGcFormFieldElement extends Components.GcFormField, HTMLStencilElement {
    }
    var HTMLGcFormFieldElement: {
        prototype: HTMLGcFormFieldElement;
        new (): HTMLGcFormFieldElement;
    };
    interface HTMLGcH1Element extends Components.GcH1, HTMLStencilElement {
    }
    var HTMLGcH1Element: {
        prototype: HTMLGcH1Element;
        new (): HTMLGcH1Element;
    };
    interface HTMLGcH2Element extends Components.GcH2, HTMLStencilElement {
    }
    var HTMLGcH2Element: {
        prototype: HTMLGcH2Element;
        new (): HTMLGcH2Element;
    };
    interface HTMLGcH3Element extends Components.GcH3, HTMLStencilElement {
    }
    var HTMLGcH3Element: {
        prototype: HTMLGcH3Element;
        new (): HTMLGcH3Element;
    };
    interface HTMLGcIconElement extends Components.GcIcon, HTMLStencilElement {
    }
    var HTMLGcIconElement: {
        prototype: HTMLGcIconElement;
        new (): HTMLGcIconElement;
    };
    interface HTMLGcInputElement extends Components.GcInput, HTMLStencilElement {
    }
    var HTMLGcInputElement: {
        prototype: HTMLGcInputElement;
        new (): HTMLGcInputElement;
    };
    interface HTMLGcLabelElement extends Components.GcLabel, HTMLStencilElement {
    }
    var HTMLGcLabelElement: {
        prototype: HTMLGcLabelElement;
        new (): HTMLGcLabelElement;
    };
    interface HTMLGcLinkElement extends Components.GcLink, HTMLStencilElement {
    }
    var HTMLGcLinkElement: {
        prototype: HTMLGcLinkElement;
        new (): HTMLGcLinkElement;
    };
    interface HTMLGcMenuElement extends Components.GcMenu, HTMLStencilElement {
    }
    var HTMLGcMenuElement: {
        prototype: HTMLGcMenuElement;
        new (): HTMLGcMenuElement;
    };
    interface HTMLGcMenuItemElement extends Components.GcMenuItem, HTMLStencilElement {
    }
    var HTMLGcMenuItemElement: {
        prototype: HTMLGcMenuItemElement;
        new (): HTMLGcMenuItemElement;
    };
    interface HTMLGcModalElement extends Components.GcModal, HTMLStencilElement {
    }
    var HTMLGcModalElement: {
        prototype: HTMLGcModalElement;
        new (): HTMLGcModalElement;
    };
    interface HTMLGcOlElement extends Components.GcOl, HTMLStencilElement {
    }
    var HTMLGcOlElement: {
        prototype: HTMLGcOlElement;
        new (): HTMLGcOlElement;
    };
    interface HTMLGcPaginationElement extends Components.GcPagination, HTMLStencilElement {
    }
    var HTMLGcPaginationElement: {
        prototype: HTMLGcPaginationElement;
        new (): HTMLGcPaginationElement;
    };
    interface HTMLGcProgressElement extends Components.GcProgress, HTMLStencilElement {
    }
    var HTMLGcProgressElement: {
        prototype: HTMLGcProgressElement;
        new (): HTMLGcProgressElement;
    };
    interface HTMLGcSelectElement extends Components.GcSelect, HTMLStencilElement {
    }
    var HTMLGcSelectElement: {
        prototype: HTMLGcSelectElement;
        new (): HTMLGcSelectElement;
    };
    interface HTMLGcSpinnerElement extends Components.GcSpinner, HTMLStencilElement {
    }
    var HTMLGcSpinnerElement: {
        prototype: HTMLGcSpinnerElement;
        new (): HTMLGcSpinnerElement;
    };
    interface HTMLGcStepElement extends Components.GcStep, HTMLStencilElement {
    }
    var HTMLGcStepElement: {
        prototype: HTMLGcStepElement;
        new (): HTMLGcStepElement;
    };
    interface HTMLGcStepsElement extends Components.GcSteps, HTMLStencilElement {
    }
    var HTMLGcStepsElement: {
        prototype: HTMLGcStepsElement;
        new (): HTMLGcStepsElement;
    };
    interface HTMLGcTabElement extends Components.GcTab, HTMLStencilElement {
    }
    var HTMLGcTabElement: {
        prototype: HTMLGcTabElement;
        new (): HTMLGcTabElement;
    };
    interface HTMLGcTabPanelElement extends Components.GcTabPanel, HTMLStencilElement {
    }
    var HTMLGcTabPanelElement: {
        prototype: HTMLGcTabPanelElement;
        new (): HTMLGcTabPanelElement;
    };
    interface HTMLGcTableElement extends Components.GcTable, HTMLStencilElement {
    }
    var HTMLGcTableElement: {
        prototype: HTMLGcTableElement;
        new (): HTMLGcTableElement;
    };
    interface HTMLGcTabsElement extends Components.GcTabs, HTMLStencilElement {
    }
    var HTMLGcTabsElement: {
        prototype: HTMLGcTabsElement;
        new (): HTMLGcTabsElement;
    };
    interface HTMLGcTabsListElement extends Components.GcTabsList, HTMLStencilElement {
    }
    var HTMLGcTabsListElement: {
        prototype: HTMLGcTabsListElement;
        new (): HTMLGcTabsListElement;
    };
    interface HTMLGcTagElement extends Components.GcTag, HTMLStencilElement {
    }
    var HTMLGcTagElement: {
        prototype: HTMLGcTagElement;
        new (): HTMLGcTagElement;
    };
    interface HTMLGcTextareaElement extends Components.GcTextarea, HTMLStencilElement {
    }
    var HTMLGcTextareaElement: {
        prototype: HTMLGcTextareaElement;
        new (): HTMLGcTextareaElement;
    };
    interface HTMLGcTooltipElement extends Components.GcTooltip, HTMLStencilElement {
    }
    var HTMLGcTooltipElement: {
        prototype: HTMLGcTooltipElement;
        new (): HTMLGcTooltipElement;
    };
    interface HTMLGcUlElement extends Components.GcUl, HTMLStencilElement {
    }
    var HTMLGcUlElement: {
        prototype: HTMLGcUlElement;
        new (): HTMLGcUlElement;
    };
    interface HTMLGcUploadElement extends Components.GcUpload, HTMLStencilElement {
    }
    var HTMLGcUploadElement: {
        prototype: HTMLGcUploadElement;
        new (): HTMLGcUploadElement;
    };
    interface HTMLElementTagNameMap {
        "gc-alert": HTMLGcAlertElement;
        "gc-button": HTMLGcButtonElement;
        "gc-cell-expandable": HTMLGcCellExpandableElement;
        "gc-cell-invalid": HTMLGcCellInvalidElement;
        "gc-checkbox": HTMLGcCheckboxElement;
        "gc-drag-container": HTMLGcDragContainerElement;
        "gc-draggable-item": HTMLGcDraggableItemElement;
        "gc-dropdown": HTMLGcDropdownElement;
        "gc-form-field": HTMLGcFormFieldElement;
        "gc-h1": HTMLGcH1Element;
        "gc-h2": HTMLGcH2Element;
        "gc-h3": HTMLGcH3Element;
        "gc-icon": HTMLGcIconElement;
        "gc-input": HTMLGcInputElement;
        "gc-label": HTMLGcLabelElement;
        "gc-link": HTMLGcLinkElement;
        "gc-menu": HTMLGcMenuElement;
        "gc-menu-item": HTMLGcMenuItemElement;
        "gc-modal": HTMLGcModalElement;
        "gc-ol": HTMLGcOlElement;
        "gc-pagination": HTMLGcPaginationElement;
        "gc-progress": HTMLGcProgressElement;
        "gc-select": HTMLGcSelectElement;
        "gc-spinner": HTMLGcSpinnerElement;
        "gc-step": HTMLGcStepElement;
        "gc-steps": HTMLGcStepsElement;
        "gc-tab": HTMLGcTabElement;
        "gc-tab-panel": HTMLGcTabPanelElement;
        "gc-table": HTMLGcTableElement;
        "gc-tabs": HTMLGcTabsElement;
        "gc-tabs-list": HTMLGcTabsListElement;
        "gc-tag": HTMLGcTagElement;
        "gc-textarea": HTMLGcTextareaElement;
        "gc-tooltip": HTMLGcTooltipElement;
        "gc-ul": HTMLGcUlElement;
        "gc-upload": HTMLGcUploadElement;
    }
}
declare namespace LocalJSX {
    interface GcAlert {
        /**
          * The content of alert
         */
        "content"?: string;
        /**
          * The type of alert: info | success | error
         */
        "type"?: string;
    }
    interface GcButton {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * Is disabled
         */
        "disabled"?: boolean;
        /**
          * The id
         */
        "gcId"?: string;
        /**
          * height
         */
        "height"?: string;
        /**
          * href
         */
        "href"?: string;
        /**
          * Icon name
         */
        "icon"?: string;
        /**
          * Emitted when click button
         */
        "onGc:click"?: (event: GcButtonCustomEvent<any>) => void;
        /**
          * padding text
         */
        "paddingText"?: string;
        /**
          * target
         */
        "target"?: string;
        /**
          * The type name
         */
        "type"?: string;
    }
    interface GcCellExpandable {
        /**
          * Disabled in step
         */
        "disabled"?: boolean;
        "fieldName"?: string;
        /**
          * index of step item from top to bottom
         */
        "index"?: string;
        "maxHeight"?: string;
        "maxWidth"?: string;
        /**
          * The mutation observer config to listen for content changes in the step item
         */
        "mutationObserverConfig"?: { childList: boolean; subtree: boolean; };
        "numberOfEntryPerPage"?: number;
        /**
          * triggered when the step item is opened
         */
        "onCloseExpandableRowsEvent"?: (event: GcCellExpandableCustomEvent<any>) => void;
        /**
          * triggered when the content of the step item changes
         */
        "onContentChanged"?: (event: GcCellExpandableCustomEvent<any>) => void;
        /**
          * triggered when the step item is opened
         */
        "onOpenExpandableRowsEvent"?: (event: GcCellExpandableCustomEvent<any>) => void;
        /**
          * step item is open or opening (css transition)
         */
        "open"?: boolean;
        /**
          * Should open in step
         */
        "shouldOpen"?: boolean;
        /**
          * The status in step
         */
        "status"?: string;
        /**
          * The tooltip message
         */
        "tooltipMessage"?: string;
        "total"?: number;
        /**
          * The total text
         */
        "totalText"?: string;
        "value"?: string;
    }
    interface GcCellInvalid {
        /**
          * The error message
         */
        "message"?: string;
        /**
          * The tooltip position
         */
        "tooltipPosition"?: string;
    }
    interface GcCheckbox {
        /**
          * Is checked ?
         */
        "checked"?: boolean;
        /**
          * The class name
         */
        "class"?: string;
        /**
          * Is disabled ?
         */
        "disabled"?: boolean;
        /**
          * The id
         */
        "gcId"?: string;
        /**
          * The name of checkbox
         */
        "gcName"?: string;
        /**
          * The label of checkbox
         */
        "label"?: string;
        /**
          * Emitted when the value has changed.
         */
        "onGc:change"?: (event: GcCheckboxCustomEvent<any>) => void;
    }
    interface GcDragContainer {
        "classContainer"?: string;
        "classDaggable"?: string;
        "group"?: string;
        /**
          * Emitted when having change in drag and drop
         */
        "onGc:drop"?: (event: GcDragContainerCustomEvent<any>) => void;
    }
    interface GcDraggableItem {
    }
    interface GcDropdown {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        "isOpen"?: boolean;
        "items"?: any[];
        /**
          * Positions    | 'auto'    | 'auto-left'    | 'auto-right'    | 'top'    | 'top-left'    | 'top-right'    | 'bottom'    | 'bottom-left'    | 'bottom-right'    | 'right'    | 'right-start'    | 'right-end'    | 'left'    | 'left-start'    | 'left-end'
         */
        "positions"?: string;
        /**
          * The button size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg';
        "trigger"?: 'click' | 'hover';
    }
    interface GcFormField {
        /**
          * Specifies the visible width of a text area
         */
        "cols"?: number;
        /**
          * Default value
         */
        "defaultValue"?: string;
        /**
          * Is disabled ?
         */
        "disabled"?: boolean;
        /**
          * Error text
         */
        "errorText"?: string;
        /**
          * The field id
         */
        "gcId"?: string;
        /**
          * The field name
         */
        "gcName"?: string;
        /**
          * Height of textarea
         */
        "height"?: string;
        /**
          * Info text
         */
        "infoText"?: string;
        /**
          * Is error
         */
        "isError"?: boolean;
        /**
          * [{   label: 'Shivaji Varma',   value: 'shivaji-varma' }]
         */
        "items"?: string | [];
        /**
          * The label name
         */
        "label"?: string;
        /**
          * Specifies the maximum number of characters allowed in the text area
         */
        "maxlength"?: number;
        /**
          * Emitted when the value has changed.
         */
        "onGc:field-change"?: (event: GcFormFieldCustomEvent<any>) => void;
        /**
          * The placeholder
         */
        "placeholder"?: string;
        /**
          * Prefix icon
         */
        "prefixIcon"?: string;
        /**
          * Resize in textarea
         */
        "resize"?: string;
        /**
          * Specifies the visible number of lines in a text area
         */
        "rows"?: number;
        /**
          * Search type Possible values are `"none"`, `"initial"`, `"contains"`, `"managed"`. Defaults to `"none"`.
         */
        "search"?: 'none' | 'initial' | 'contains' | 'managed';
        /**
          * The input type
         */
        "type"?: string;
        /**
          * The input value
         */
        "value"?: string;
    }
    interface GcH1 {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The id
         */
        "gcId"?: string;
    }
    interface GcH2 {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The id
         */
        "gcId"?: string;
    }
    interface GcH3 {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The id
         */
        "gcId"?: string;
    }
    interface GcIcon {
        "color"?: string;
        "fontWeight"?: string;
        "name"?: string;
        /**
          * The Icon size. Possible values are: `"sm"`, `"md"`, `"lg"`, `"xl"` and size in pixel. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg' | 'xl' | string;
    }
    interface GcInput {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * Is disabled ?
         */
        "disabled"?: boolean;
        /**
          * The id
         */
        "gcId"?: string;
        /**
          * The name of input
         */
        "gcName"?: string;
        /**
          * Is error
         */
        "isError"?: boolean;
        /**
          * Emitted when the value has changed.
         */
        "onGc:change"?: (event: GcInputCustomEvent<any>) => void;
        /**
          * The placeholder
         */
        "placeholder"?: string;
        /**
          * The name of input
         */
        "prefixIcon"?: string;
        /**
          * The input type
         */
        "type"?: string;
        /**
          * The input value
         */
        "value"?: string;
    }
    interface GcLabel {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * Label for what component
         */
        "gcFor"?: string;
        /**
          * The id
         */
        "gcId"?: string;
    }
    interface GcLink {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The color of link
         */
        "color"?: string;
        /**
          * The id
         */
        "gcId"?: string;
        /**
          * Go to link
         */
        "gcTo"?: string;
        /**
          * Icon name
         */
        "icon"?: string;
        /**
          * Size of link
         */
        "size"?: string;
        /**
          * target link
         */
        "target"?: string;
    }
    interface GcMenu {
        "empty"?: boolean;
        "emptyState"?: any;
        "showLoader"?: boolean;
        "value"?: string | number;
    }
    interface GcMenuItem {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The color of text
         */
        "color"?: string;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        /**
          * The color of dot
         */
        "dot"?: string;
        /**
          * The id
         */
        "gcId"?: string;
        /**
          * The label
         */
        "label"?: string;
        /**
          * Emitted when the menu item is clicked.
         */
        "onGc:menu-item-click"?: (event: GcMenuItemCustomEvent<any>) => void;
        /**
          * Menu item selection state.
         */
        "selected"?: boolean;
        /**
          * The menu item value.
         */
        "value"?: string | number | null;
    }
    interface GcModal {
        /**
          * Header Icon
         */
        "headerIcon"?: string;
        /**
          * Is custom content?
         */
        "isCustomContent"?: boolean;
        "onGc:modal-open"?: (event: GcModalCustomEvent<any>) => void;
        /**
          * Is open?
         */
        "open"?: boolean;
        /**
          * Is transparent?
         */
        "transparent"?: boolean;
        /**
          * Width of modal
         */
        "width"?: string;
    }
    interface GcOl {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The id
         */
        "gcId"?: string;
    }
    interface GcPagination {
        /**
          * The page size
         */
        "activePage"?: number;
        /**
          * Emitted when the value has changed.
         */
        "onGc:change-page"?: (event: GcPaginationCustomEvent<any>) => void;
        /**
          * The page size
         */
        "pageSize"?: number;
        /**
          * The total
         */
        "total"?: number;
    }
    interface GcProgress {
        /**
          * The percent of progress
         */
        "percent"?: number;
        /**
          * The width of progress
         */
        "width"?: string;
    }
    interface GcSelect {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * If `true`, a clear icon will appear in the input when there is a value. Clicking it clears the input.
         */
        "clearable"?: boolean;
        "configAria"?: any;
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `goatChange` event after each keystroke.
         */
        "debounce"?: number;
        /**
          * Default value
         */
        "defaultValue"?: string;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        /**
          * The id
         */
        "gcId"?: string;
        /**
          * Is error
         */
        "isError"?: boolean;
        "isOpen"?: boolean;
        /**
          * [{   label: 'Shivaji Varma',   value: 'shivaji-varma' }]
         */
        "items"?: string | [];
        "multiple"?: boolean;
        /**
          * Emitted when the action button is clicked..
         */
        "onGc:action-click"?: (event: GcSelectCustomEvent<any>) => void;
        /**
          * Emitted when the value has changed.
         */
        "onGc:change"?: (event: GcSelectCustomEvent<any>) => void;
        /**
          * Emitted when a keyboard input occurred.
         */
        "onGc:search"?: (event: GcSelectCustomEvent<any>) => void;
        /**
          * The input field placeholder.
         */
        "placeholder"?: string;
        "positions"?: string;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "readonly"?: boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
         */
        "required"?: boolean;
        /**
          * Search type Possible values are `"none"`, `"initial"`, `"contains"`, `"managed"`. Defaults to `"none"`.
         */
        "search"?: 'none' | 'initial' | 'contains' | 'managed';
        "showLoader"?: boolean;
        /**
          * The select input size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The input state. Possible values are: `"success"`, `"error"`, `"warning"`, 'default'. Defaults to `"default"`.
         */
        "state"?: 'success' | 'error' | 'warning' | 'default';
        /**
          * The input field value.
         */
        "value"?: string | number;
    }
    interface GcSpinner {
        /**
          * Is float above background
         */
        "isFloat"?: boolean;
    }
    interface GcStep {
        /**
          * Customize in step opening
         */
        "customOpen"?: boolean;
        /**
          * Disabled in step
         */
        "disabled"?: boolean;
        /**
          * The icon in step
         */
        "icon"?: string;
        /**
          * index of step item from top to bottom
         */
        "index"?: string;
        "maxHeight"?: string;
        /**
          * The mutation observer config to listen for content changes in the step item
         */
        "mutationObserverConfig"?: { childList: boolean; subtree: boolean; };
        /**
          * triggered before the step item is opened
         */
        "onBeforeOpenEvent"?: (event: GcStepCustomEvent<any>) => void;
        /**
          * triggered when the step item is opened
         */
        "onCloseEvent"?: (event: GcStepCustomEvent<any>) => void;
        /**
          * triggered when the content of the step item changes
         */
        "onContentChanged"?: (event: GcStepCustomEvent<any>) => void;
        /**
          * triggered when the step item is opened
         */
        "onOpenEvent"?: (event: GcStepCustomEvent<any>) => void;
        /**
          * step item is open or opening (css transition)
         */
        "open"?: boolean;
        /**
          * Should open in step
         */
        "shouldOpen"?: boolean;
        /**
          * The status in step
         */
        "status"?: string;
    }
    interface GcSteps {
        "customOpen"?: boolean;
        /**
          * triggered before the step item is active
         */
        "onGc:before-step-change"?: (event: GcStepsCustomEvent<any>) => void;
        /**
          * triggered when the step item is active
         */
        "onGc:step-change"?: (event: GcStepsCustomEvent<any>) => void;
    }
    interface GcTab {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
         */
        "disabled"?: boolean;
        /**
          * The icon of tab.
         */
        "icon"?: string;
        /**
          * On click of tab, a CustomEvent 'gc:tab-click' will be triggered.
         */
        "onGc:tab-click"?: (event: GcTabCustomEvent<any>) => void;
        /**
          * Button selection state.
         */
        "selected"?: boolean;
        /**
          * Show loader.
         */
        "showLoader"?: boolean;
        "target"?: string;
        "value"?: string;
    }
    interface GcTabPanel {
        "active"?: boolean;
        "value"?: string;
    }
    interface GcTable {
        "background"?: string;
        /**
          * Grid columns configuration. [ {   "name":"name",   "label":"Name",   "width":300,   "fixed":true  }, {   "name":"age",   "label":"Age" } ]
         */
        "columns"?: string | any[];
        "customEmptyState"?: string;
        "customRows"?: string[];
        "customRowsBackground"?: string;
        "customRowsBorder"?: string;
        /**
          * Grid data to display on table [{  'id': '5e7118ddce4b3d577956457f',  'age': 21,  'name': 'John',  'company': 'India',  'email': 'john@example.com',  'phone': '+1 (839) 560-3581',  'address': '326 Irving Street, Grimsley, Texas, 4048'  }]
         */
        "data"?: string | any[];
        "emptyState"?: any;
        "gcId"?: string;
        "isBordered"?: boolean;
        "isCustomHeader"?: boolean;
        "isExpandable"?: boolean;
        "isLoading"?: false;
        "isNoBorderedAll"?: boolean;
        "isNoBorderedEmptyState"?: boolean;
        "isStripe"?: boolean;
        "keyField"?: string;
        "loadingGroupIndex"?: any[];
        "maxHeight"?: string;
        "maxWidthInExpandRow"?: string;
        "onGc:change-page"?: (event: GcTableCustomEvent<any>) => void;
        "onGc:clear-empty-state"?: (event: GcTableCustomEvent<any>) => void;
        "onGc:sort"?: (event: GcTableCustomEvent<any>) => void;
        "onGc:table-cell-click"?: (event: GcTableCustomEvent<any>) => void;
        "onGc:table-collapse-change"?: (event: GcTableCustomEvent<any>) => void;
        "onGc:table-select-change"?: (event: GcTableCustomEvent<any>) => void;
        "onGc:table-setting-change"?: (event: GcTableCustomEvent<any>) => void;
        "page"?: number;
        "pageSize"?: number;
        "paginate"?: boolean;
        "selectedRowKeys"?: string[];
        "selectionType"?: 'checkbox' | undefined;
        "serverSide"?: boolean;
        "settingColumns"?: boolean;
        "settingTable"?: any;
        "sortBy"?: string;
        "sortOrder"?: 'asc' | 'desc' | '';
        "sortable"?: boolean;
        "totalItems"?: number;
        "treeData"?: string | any[];
    }
    interface GcTabs {
        /**
          * On click of tab, a CustomEvent 'gc:tab-click' will be triggered.
         */
        "onGc:tab-change"?: (event: GcTabsCustomEvent<any>) => void;
    }
    interface GcTabsList {
        "managed"?: boolean;
        "variant"?: 'line' | 'contained';
    }
    interface GcTag {
        /**
          * The background of badge
         */
        "background"?: string;
        /**
          * The border color of badge
         */
        "borderColor"?: string;
        /**
          * The border width of badge
         */
        "borderWidth"?: string;
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The color of badge
         */
        "color"?: string;
        /**
          * The id
         */
        "gcId"?: string;
        /**
          * The width of badge
         */
        "height"?: string;
        /**
          * The type name
         */
        "type"?: string;
        /**
          * The width of badge
         */
        "width"?: string;
    }
    interface GcTextarea {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * Specifies the visible width of a text area
         */
        "cols"?: number;
        /**
          * Is disabled ?
         */
        "disabled"?: boolean;
        /**
          * The id
         */
        "gcId"?: string;
        /**
          * The name of input
         */
        "gcName"?: string;
        /**
          * Height of textarea
         */
        "height"?: string;
        /**
          * Is error
         */
        "isError"?: boolean;
        /**
          * Specifies the maximum number of characters allowed in the text area
         */
        "maxlength"?: number;
        /**
          * Emitted when the value has changed.
         */
        "onGc:change"?: (event: GcTextareaCustomEvent<any>) => void;
        /**
          * The placeholder
         */
        "placeholder"?: string;
        /**
          * Resize in textarea
         */
        "resize"?: string;
        /**
          * Specifies the visible number of lines in a text area
         */
        "rows"?: number;
        /**
          * The input value
         */
        "value"?: string;
    }
    interface GcTooltip {
        /**
          * The content
         */
        "content"?: any;
        /**
          * Is Copy Text?
         */
        "isCopyText"?: any;
        /**
          * Is Long Text?
         */
        "isLongText"?: boolean;
        /**
          * Is Popover?
         */
        "isPopover"?: boolean;
        /**
          * Is Toggle?
         */
        "isToggle"?: boolean;
        "onGc:toggle-tooltip"?: (event: GcTooltipCustomEvent<any>) => void;
        /**
          * Right position
         */
        "rightPos"?: string;
        /**
          * Top position
         */
        "topPos"?: string;
    }
    interface GcUl {
        /**
          * The class name
         */
        "class"?: string;
        /**
          * The id
         */
        "gcId"?: string;
    }
    interface GcUpload {
        /**
          * Accept type
         */
        "acceptType"?: string;
        /**
          * Disabled
         */
        "disabled"?: boolean;
        /**
          * Custom how to display
         */
        "isCustom"?: boolean;
        "onGc:upload-completed"?: (event: GcUploadCustomEvent<any>) => void;
        "onGc:upload-progress"?: (event: GcUploadCustomEvent<any>) => void;
        "onGc:uploaded-file"?: (event: GcUploadCustomEvent<any>) => void;
        /**
          * Option
         */
        "option"?: {};
        /**
          * Width of upload
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "gc-alert": GcAlert;
        "gc-button": GcButton;
        "gc-cell-expandable": GcCellExpandable;
        "gc-cell-invalid": GcCellInvalid;
        "gc-checkbox": GcCheckbox;
        "gc-drag-container": GcDragContainer;
        "gc-draggable-item": GcDraggableItem;
        "gc-dropdown": GcDropdown;
        "gc-form-field": GcFormField;
        "gc-h1": GcH1;
        "gc-h2": GcH2;
        "gc-h3": GcH3;
        "gc-icon": GcIcon;
        "gc-input": GcInput;
        "gc-label": GcLabel;
        "gc-link": GcLink;
        "gc-menu": GcMenu;
        "gc-menu-item": GcMenuItem;
        "gc-modal": GcModal;
        "gc-ol": GcOl;
        "gc-pagination": GcPagination;
        "gc-progress": GcProgress;
        "gc-select": GcSelect;
        "gc-spinner": GcSpinner;
        "gc-step": GcStep;
        "gc-steps": GcSteps;
        "gc-tab": GcTab;
        "gc-tab-panel": GcTabPanel;
        "gc-table": GcTable;
        "gc-tabs": GcTabs;
        "gc-tabs-list": GcTabsList;
        "gc-tag": GcTag;
        "gc-textarea": GcTextarea;
        "gc-tooltip": GcTooltip;
        "gc-ul": GcUl;
        "gc-upload": GcUpload;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gc-alert": LocalJSX.GcAlert & JSXBase.HTMLAttributes<HTMLGcAlertElement>;
            "gc-button": LocalJSX.GcButton & JSXBase.HTMLAttributes<HTMLGcButtonElement>;
            "gc-cell-expandable": LocalJSX.GcCellExpandable & JSXBase.HTMLAttributes<HTMLGcCellExpandableElement>;
            "gc-cell-invalid": LocalJSX.GcCellInvalid & JSXBase.HTMLAttributes<HTMLGcCellInvalidElement>;
            "gc-checkbox": LocalJSX.GcCheckbox & JSXBase.HTMLAttributes<HTMLGcCheckboxElement>;
            "gc-drag-container": LocalJSX.GcDragContainer & JSXBase.HTMLAttributes<HTMLGcDragContainerElement>;
            "gc-draggable-item": LocalJSX.GcDraggableItem & JSXBase.HTMLAttributes<HTMLGcDraggableItemElement>;
            "gc-dropdown": LocalJSX.GcDropdown & JSXBase.HTMLAttributes<HTMLGcDropdownElement>;
            "gc-form-field": LocalJSX.GcFormField & JSXBase.HTMLAttributes<HTMLGcFormFieldElement>;
            "gc-h1": LocalJSX.GcH1 & JSXBase.HTMLAttributes<HTMLGcH1Element>;
            "gc-h2": LocalJSX.GcH2 & JSXBase.HTMLAttributes<HTMLGcH2Element>;
            "gc-h3": LocalJSX.GcH3 & JSXBase.HTMLAttributes<HTMLGcH3Element>;
            "gc-icon": LocalJSX.GcIcon & JSXBase.HTMLAttributes<HTMLGcIconElement>;
            "gc-input": LocalJSX.GcInput & JSXBase.HTMLAttributes<HTMLGcInputElement>;
            "gc-label": LocalJSX.GcLabel & JSXBase.HTMLAttributes<HTMLGcLabelElement>;
            "gc-link": LocalJSX.GcLink & JSXBase.HTMLAttributes<HTMLGcLinkElement>;
            "gc-menu": LocalJSX.GcMenu & JSXBase.HTMLAttributes<HTMLGcMenuElement>;
            "gc-menu-item": LocalJSX.GcMenuItem & JSXBase.HTMLAttributes<HTMLGcMenuItemElement>;
            "gc-modal": LocalJSX.GcModal & JSXBase.HTMLAttributes<HTMLGcModalElement>;
            "gc-ol": LocalJSX.GcOl & JSXBase.HTMLAttributes<HTMLGcOlElement>;
            "gc-pagination": LocalJSX.GcPagination & JSXBase.HTMLAttributes<HTMLGcPaginationElement>;
            "gc-progress": LocalJSX.GcProgress & JSXBase.HTMLAttributes<HTMLGcProgressElement>;
            "gc-select": LocalJSX.GcSelect & JSXBase.HTMLAttributes<HTMLGcSelectElement>;
            "gc-spinner": LocalJSX.GcSpinner & JSXBase.HTMLAttributes<HTMLGcSpinnerElement>;
            "gc-step": LocalJSX.GcStep & JSXBase.HTMLAttributes<HTMLGcStepElement>;
            "gc-steps": LocalJSX.GcSteps & JSXBase.HTMLAttributes<HTMLGcStepsElement>;
            "gc-tab": LocalJSX.GcTab & JSXBase.HTMLAttributes<HTMLGcTabElement>;
            "gc-tab-panel": LocalJSX.GcTabPanel & JSXBase.HTMLAttributes<HTMLGcTabPanelElement>;
            "gc-table": LocalJSX.GcTable & JSXBase.HTMLAttributes<HTMLGcTableElement>;
            "gc-tabs": LocalJSX.GcTabs & JSXBase.HTMLAttributes<HTMLGcTabsElement>;
            "gc-tabs-list": LocalJSX.GcTabsList & JSXBase.HTMLAttributes<HTMLGcTabsListElement>;
            "gc-tag": LocalJSX.GcTag & JSXBase.HTMLAttributes<HTMLGcTagElement>;
            "gc-textarea": LocalJSX.GcTextarea & JSXBase.HTMLAttributes<HTMLGcTextareaElement>;
            "gc-tooltip": LocalJSX.GcTooltip & JSXBase.HTMLAttributes<HTMLGcTooltipElement>;
            "gc-ul": LocalJSX.GcUl & JSXBase.HTMLAttributes<HTMLGcUlElement>;
            "gc-upload": LocalJSX.GcUpload & JSXBase.HTMLAttributes<HTMLGcUploadElement>;
        }
    }
}
